version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    exclude-paths:
      - "_examples/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"